"""Marlin G-code generation for a Z-axis pen plotter."""

from __future__ import annotations

from .models import PageConfig, PenConfig, Polylines


def _validate_bounds(polylines: Polylines, page: PageConfig) -> None:
    tolerance = 0.01
    for line_number, line in enumerate(polylines, start=1):
        for point_number, (x, y) in enumerate(line, start=1):
            if not (-tolerance <= x <= page.width_mm + tolerance):
                raise ValueError(
                    f"X={x:.3f} at line {line_number}, point {point_number} "
                    f"is outside the {page.width_mm:.3f} mm page."
                )
            if not (-tolerance <= y <= page.height_mm + tolerance):
                raise ValueError(
                    f"Y={y:.3f} at line {line_number}, point {point_number} "
                    f"is outside the {page.height_mm:.3f} mm page."
                )


def polylines_to_gcode(
    polylines: Polylines,
    page: PageConfig,
    pen: PenConfig,
    *,
    title: str = "Printrbot plot job",
) -> str:
    """Create absolute-coordinate Marlin G-code.

    Homing is opt-in. The caller must calibrate Z-up and Z-down values before
    enabling physical plotting.
    """

    page.validate()
    pen.validate()
    _validate_bounds(polylines, page)

    lines = [
        f"; {title}",
        "; Generated by printrbot-penplotter",
        "G21 ; millimeters",
        "G90 ; absolute positioning",
        "M400 ; finish queued motion",
    ]

    if pen.home_before_plot:
        lines.extend(["G28 ; home all configured axes", "M400"])

    lines.append(f"G0 Z{pen.z_up_mm:.3f} F{pen.z_feed_mm_min:.1f} ; pen up")

    for stroke_index, stroke in enumerate(polylines, start=1):
        if len(stroke) < 2:
            continue
        start_x, start_y = stroke[0]
        lines.extend(
            [
                f"; stroke {stroke_index}",
                f"G0 X{start_x:.3f} Y{start_y:.3f} F{pen.travel_feed_mm_min:.1f}",
                f"G0 Z{pen.z_down_mm:.3f} F{pen.z_feed_mm_min:.1f} ; pen down",
            ]
        )
        for x, y in stroke[1:]:
            lines.append(f"G1 X{x:.3f} Y{y:.3f} F{pen.draw_feed_mm_min:.1f}")
        lines.append(f"G0 Z{pen.z_up_mm:.3f} F{pen.z_feed_mm_min:.1f} ; pen up")

    lines.extend(["M400", f"G0 Z{pen.z_up_mm:.3f} F{pen.z_feed_mm_min:.1f}"])

    if pen.park_x_mm is not None and pen.park_y_mm is not None:
        lines.append(
            f"G0 X{pen.park_x_mm:.3f} Y{pen.park_y_mm:.3f} "
            f"F{pen.travel_feed_mm_min:.1f} ; park"
        )

    lines.extend(["M400", "; end of job", ""])
    return "\n".join(lines)
