"""Marlin G-code generation for a Z-axis pen plotter."""

from __future__ import annotations

import math

from .geometry import validate_polylines
from .models import MachineConfig, PageConfig, PenConfig, Polylines
from .optimize import segment_is_corner_slowed

MAX_GCODE_COMMANDS = 2_000_000


def _validate_bounds(
    polylines: Polylines,
    page: PageConfig,
    machine: MachineConfig,
) -> None:
    validate_polylines(polylines)
    tolerance = 0.01
    page_x_min = page.origin_x_mm
    page_x_max = page.origin_x_mm + page.width_mm
    page_y_min = page.origin_y_mm
    page_y_max = page.origin_y_mm + page.height_mm

    for line_number, line in enumerate(polylines, start=1):
        for point_number, (x, y) in enumerate(line, start=1):
            if not math.isfinite(x) or not math.isfinite(y):
                raise ValueError(
                    f"Non-finite coordinate at stroke {line_number}, point {point_number}."
                )
            if not (machine.x_min_mm - tolerance <= x <= machine.x_max_mm + tolerance):
                raise ValueError(
                    f"X={x:.3f} at stroke {line_number}, point {point_number} "
                    "is outside machine limits."
                )
            if not (machine.y_min_mm - tolerance <= y <= machine.y_max_mm + tolerance):
                raise ValueError(
                    f"Y={y:.3f} at stroke {line_number}, point {point_number} "
                    "is outside machine limits."
                )
            if not (page_x_min - tolerance <= x <= page_x_max + tolerance):
                raise ValueError(
                    f"X={x:.3f} at stroke {line_number}, point {point_number} "
                    "is outside the configured paper rectangle."
                )
            if not (page_y_min - tolerance <= y <= page_y_max + tolerance):
                raise ValueError(
                    f"Y={y:.3f} at stroke {line_number}, point {point_number} "
                    "is outside the configured paper rectangle."
                )


def polylines_to_gcode(
    polylines: Polylines,
    page: PageConfig,
    pen: PenConfig,
    machine: MachineConfig | None = None,
    *,
    title: str = "Printrbot plot job",
) -> str:
    """Create absolute-coordinate Marlin G-code.

    Homing is opt-in. When ``home_before_plot`` is enabled, the generated
    hardware job establishes all axes with ``G28`` before drawing and, after
    raising the pen, re-homes X/Y at the end. Z is deliberately not re-homed
    after drawing because this plotter's Z-min home direction moves the pen
    toward the paper. ``air_plot`` traces every XY path while keeping the pen at
    ``z_up_mm``. Drawing feed automatically slows on segments touching corners
    sharper than ``corner_angle_deg``.
    """

    machine = machine or MachineConfig()
    machine.validate()
    page.validate(machine)
    pen.validate(machine)
    _validate_bounds(polylines, page, machine)

    lines = [
        f"; {title}",
        "; Generated by printrbot-penplotter",
        f"; mode: {'AIR PLOT' if pen.air_plot else 'PEN PLOT'}",
        f"; corner feed: {pen.corner_feed_mm_min:.1f} below {pen.corner_angle_deg:.1f} deg",
        "G21 ; millimeters",
        "G90 ; absolute positioning",
        "M400 ; finish queued motion",
    ]

    if pen.home_before_plot:
        lines.extend(["G28 ; home X/Y/Z before plot", "M400"])

    lines.append(f"G0 Z{pen.z_up_mm:.3f} F{pen.z_feed_mm_min:.1f} ; pen up")

    for stroke_index, stroke in enumerate(polylines, start=1):
        if len(stroke) < 2:
            continue
        start_x, start_y = stroke[0]
        lines.extend(
            [
                f"; stroke {stroke_index}",
                f"G0 X{start_x:.3f} Y{start_y:.3f} F{pen.travel_feed_mm_min:.1f}",
            ]
        )
        if pen.air_plot:
            lines.append(f"G0 Z{pen.z_up_mm:.3f} F{pen.z_feed_mm_min:.1f} ; air plot")
        else:
            lines.append(f"G0 Z{pen.z_down_mm:.3f} F{pen.z_feed_mm_min:.1f} ; pen down")

        for segment_index, (x, y) in enumerate(stroke[1:]):
            feed = pen.draw_feed_mm_min
            if segment_is_corner_slowed(stroke, segment_index, pen.corner_angle_deg):
                feed = min(feed, pen.corner_feed_mm_min)
            lines.append(f"G1 X{x:.3f} Y{y:.3f} F{feed:.1f}")

        lines.append(f"G0 Z{pen.z_up_mm:.3f} F{pen.z_feed_mm_min:.1f} ; pen up")
        if len(lines) > MAX_GCODE_COMMANDS:
            raise ValueError(
                f"Generated job exceeds the {MAX_GCODE_COMMANDS} command safety limit."
            )

    # Standard safe end sequence: wait, guarantee pen-up, optionally park, then
    # re-home only the planar axes when the job was configured to home. Never
    # G28 Z after ink motion.
    lines.extend(
        [
            "; end sequence: pen-up and wait" if not pen.home_before_plot else "; end sequence: pen-up, wait, and X/Y re-home",
            "M400 ; finish drawing motion",
            f"G0 Z{pen.z_up_mm:.3f} F{pen.z_feed_mm_min:.1f} ; final pen up",
            "M400 ; confirm pen-up motion",
        ]
    )

    if pen.park_x_mm is not None and pen.park_y_mm is not None:
        lines.extend(
            [
                f"G0 X{pen.park_x_mm:.3f} Y{pen.park_y_mm:.3f} "
                f"F{pen.travel_feed_mm_min:.1f} ; park",
                "M400 ; finish park motion",
            ]
        )

    if pen.home_before_plot:
        lines.extend(
            [
                "G28 X Y ; re-home X/Y with pen safely raised",
                "M400 ; finish end homing",
            ]
        )

    lines.extend(["; end of job", ""])
    return "\n".join(lines)
