"""Shared browser theme for the notes, raster, and Studio surfaces."""

LAB_THEME_CSS = r"""
<style id="printrbot-lab-theme">
:root{color-scheme:dark;--lab-bg:#08111a;--lab-panel:#101c28;--lab-raised:#142536;--lab-border:#29445a;--lab-strong:#3a6079;--lab-text:#edf6fb;--lab-muted:#93aabd;--lab-accent:#79d4ff;--lab-teal:#55c8b0;--lab-warning:#f6c667;--lab-danger:#ff8994}
html,body{background:var(--lab-bg)!important;color:var(--lab-text)!important}body{background-image:radial-gradient(circle at 12% 0%,rgba(73,153,190,.12),transparent 34rem)!important}h1,h2,h3,strong{color:var(--lab-text)}p,.hint,.tabs,.visual-subtitle,.step-panel>p{color:var(--lab-muted)!important}
.card,.step-panel,.step-visual,.style-choice,.control-section,.group{background:var(--lab-panel)!important;border-color:var(--lab-border)!important;box-shadow:0 14px 34px rgba(0,0,0,.22)!important}.group,.control-section{background:var(--lab-raised)!important}
.app-tabs{background:#0d1a26!important;border:1px solid var(--lab-border);width:fit-content!important}.app-tabs a{color:var(--lab-muted)!important}.app-tabs a:hover{background:#193247!important;color:var(--lab-text)!important}.app-tabs a.active{background:var(--lab-accent)!important;color:#061018!important}
label,.check,summary{color:#c5d5e1!important}textarea,input,select,button{border-color:var(--lab-strong)!important;background:#0b1722!important;color:var(--lab-text)!important}textarea::placeholder,input::placeholder{color:#71899c!important}textarea:focus,input:focus,select:focus{border-color:var(--lab-accent)!important;box-shadow:0 0 0 3px rgba(121,212,255,.15)}
button{background:var(--lab-teal)!important;color:#061018!important;border-color:var(--lab-teal)!important}button:hover:not(:disabled){filter:brightness(1.08)}button.secondary,.secondary{background:#29465d!important;color:var(--lab-text)!important;border-color:var(--lab-strong)!important}button.safe{background:#9c7831!important;color:#fff8df!important;border-color:#c29a43!important}button:disabled{background:#233444!important;color:#7890a2!important;border-color:#30495d!important}
.workflow-hint,.selected-style{background:#123346!important;color:#c8eaff!important;border:1px solid #2c6683}.status{color:var(--lab-teal)!important}.status.busy{background:#3b321a!important;color:var(--lab-warning)!important}.status.error,.warning{background:#3b2026!important;color:#ffb3ba!important;border-color:#79414a!important}
.workflow-card{display:flex;flex-direction:column;gap:14px}.workflow-step{padding:14px;border:1px solid var(--lab-border);border-radius:12px;background:var(--lab-raised)}.workflow-step h2{margin:2px 0 10px;font-size:17px}.step-kicker{color:var(--lab-accent)!important;font:700 11px/1.2 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.12em}.workflow-step .secondary{margin-top:10px}.advanced-step{margin:0;padding:0;background:var(--lab-panel)!important}.advanced-step>summary{padding:14px;list-style:none}.advanced-step>summary::-webkit-details-marker{display:none}.advanced-step>summary:before{content:'+';display:inline-block;width:18px;color:var(--lab-accent);font-size:18px}.advanced-step[open]>summary:before{content:'−'}.neural-controls{margin-top:10px}.workflow-card>.status{margin-top:0}
.workflow-step h2{color:var(--lab-text)!important}.workflow-step label,.workflow-step summary{color:#d6e2ea!important}.workflow-step .hint,.workflow-step .control-note{color:#a8b9c5!important}.workflow-step select{color:var(--lab-text)!important;background:#0b1722!important}.workflow-step select option{background:#0b1722;color:var(--lab-text)}#handwritingControls[hidden]{display:none!important}
.advanced-toggle,.process-tab{background:#0d1a26!important;color:var(--lab-text)!important;border-color:var(--lab-border)!important}.process-tab span{color:var(--lab-muted)!important}.process-tab.active,.stage-tab.active{background:var(--lab-accent)!important;color:#061018!important;border-color:var(--lab-accent)!important}.process-tab.active span{color:#173344!important}
.pane,.view{background:#0b1722!important;border-color:var(--lab-border)!important;color:var(--lab-text)!important}.pane img,.pane svg,.view img,.view svg,#preview svg{background:#fff}#preview{background:#0a1621!important;border:1px solid var(--lab-border)}
.floating-actions{background:rgba(16,28,40,.96)!important;border-color:var(--lab-strong)!important;box-shadow:0 12px 34px rgba(0,0,0,.38)!important}.floating-actions button.primary,.step-generate{background:var(--lab-accent)!important;color:#061018!important;border-color:var(--lab-accent)!important}.step-stop{background:#321b23!important;color:var(--lab-danger)!important;border-color:#75404b!important}
.studio-loading{background:rgba(3,9,15,.78)!important}.studio-loading-card{background:var(--lab-panel)!important;border-color:var(--lab-strong)!important;box-shadow:0 16px 46px rgba(0,0,0,.48)!important}.studio-loading-card span{color:var(--lab-muted)!important}#studioVersion{color:var(--lab-muted)!important;background:rgba(16,28,40,.94)!important;border-color:var(--lab-border)!important}pre{color:#a9ddff!important}
@media(max-width:700px){.app-tabs{width:100%!important}.app-tabs a{flex:1;text-align:center}}
</style>
"""
